### ISSUE TITLE
Crash when viewing image

### ISSUE THREAD

**Issue by xasx** [WangDaYeeeeee/Mysplash#24]
After an update to the latest version, I encounter an App crash when I click on an image to view its details.

App Version: 2.9.3
Android OS: 7.1/LineageOS 14.1
Reproducibility: always
STR: Tap an image in the stream.

From my logcat, I can see this NPE:

```
java.lang.NullPointerException: Attempt to read from field 'java.util.List com.wangdaye.mysplash._common.data.entity.unsplash.Photo$RelatedPhotos.results' on a null object reference
	at com.wangdaye.mysplash._common.ui.adapter.PhotoInfoAdapter.buildTypeList(PhotoInfoAdapter.java:125)
```

Some more context (stripped down a little bit):
```
02-22 08:45:59.053 I/ActivityManager( 3109): Start proc 20506:com.wangdaye.mysplash/u0a389 for activity com.wangdaye.mysplash/.main.view.activity.MainActivity
02-22 08:45:59.148 W/System  (20506): ClassLoader referenced unknown path: /data/app/com.wangdaye.mysplash-2/lib/arm
02-22 08:45:59.188 W/art     (20506): Before Android 4.1, method android.graphics.PorterDuffColorFilter android.support.graphics.drawable.VectorDrawableCompat.updateTintFilter(android.graphics.PorterDuffColorFilter, android.content.res.ColorStateList, android.graphics.PorterDuff$Mode) would have incorrectly overridden the package-private method in android.graphics.drawable.Drawable
02-22 08:45:59.642 I/AppCompatViewInflater(20506): app:theme is now deprecated. Please move to using android:theme instead.
02-22 08:46:00.017 I/ActivityManager( 3109): Displayed com.wangdaye.mysplash/.main.view.activity.MainActivity: +977ms
02-22 08:46:01.455 I/ActivityManager( 3109): START u0 {cmp=com.wangdaye.mysplash/.photo.view.activity.PhotoActivity (has extras)} from uid 10389 on display 0
02-22 08:46:01.931 I/ActivityManager( 3109): Displayed com.wangdaye.mysplash/.photo.view.activity.PhotoActivity: +340ms
02-22 08:46:02.003 D/AndroidRuntime(20506): Shutting down VM
02-22 08:46:02.004 E/AndroidRuntime(20506): FATAL EXCEPTION: main
02-22 08:46:02.004 E/AndroidRuntime(20506): Process: com.wangdaye.mysplash, PID: 20506
02-22 08:46:02.004 E/AndroidRuntime(20506): java.lang.NullPointerException: Attempt to read from field 'java.util.List com.wangdaye.mysplash._common.data.entity.unsplash.Photo$RelatedPhotos.results' on a null object reference
02-22 08:46:02.004 E/AndroidRuntime(20506): 	at com.wangdaye.mysplash._common.ui.adapter.PhotoInfoAdapter.buildTypeList(PhotoInfoAdapter.java:125)
02-22 08:46:02.004 E/AndroidRuntime(20506): 	at com.wangdaye.mysplash._common.ui.adapter.PhotoInfoAdapter.updatePhoto(PhotoInfoAdapter.java:137)
02-22 08:46:02.004 E/AndroidRuntime(20506): 	at com.wangdaye.mysplash.photo.view.activity.PhotoActivity.requestPhotoSuccess(PhotoActivity.java:579)
02-22 08:46:02.004 E/AndroidRuntime(20506): 	at com.wangdaye.mysplash.photo.presenter.PhotoInfoImplementor$OnRequestPhotoDetailsListener.onRequestSinglePhotoSuccess(PhotoInfoImplementor.java:107)
02-22 08:46:02.004 E/AndroidRuntime(20506): 	at com.wangdaye.mysplash._common.data.service.PhotoInfoService$1.onResponse(PhotoInfoService.java:32)
02-22 08:46:02.004 E/AndroidRuntime(20506): 	at retrofit2.ExecutorCallAdapterFactory$ExecutorCallbackCall$1$1.run(ExecutorCallAdapterFactory.java:68)
02-22 08:46:02.004 E/AndroidRuntime(20506): 	at android.os.Handler.handleCallback(Handler.java:751)
02-22 08:46:02.004 E/AndroidRuntime(20506): 	at android.os.Handler.dispatchMessage(Handler.java:95)
02-22 08:46:02.004 E/AndroidRuntime(20506): 	at android.os.Looper.loop(Looper.java:154)
02-22 08:46:02.004 E/AndroidRuntime(20506): 	at android.app.ActivityThread.main(ActivityThread.java:6176)
02-22 08:46:02.004 E/AndroidRuntime(20506): 	at java.lang.reflect.Method.invoke(Native Method)
02-22 08:46:02.004 E/AndroidRuntime(20506): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:888)
02-22 08:46:02.004 E/AndroidRuntime(20506): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:778)
02-22 08:46:02.006 W/ActivityManager( 3109):   Force finishing activity com.wangdaye.mysplash/.photo.view.activity.PhotoActivity
02-22 08:46:02.010 W/ActivityManager( 3109):   Force finishing activity com.wangdaye.mysplash/.main.view.activity.MainActivity
02-22 08:46:02.082 I/OpenGLRenderer( 3109): Initialized EGL, version 1.4
02-22 08:46:02.082 D/OpenGLRenderer( 3109): Swap behavior 1
02-22 08:46:02.511 W/ActivityManager( 3109): Activity pause timeout for ActivityRecord{63bd373 u0 com.wangdaye.mysplash/.photo.view.activity.PhotoActivity t275 f}
```

**Comment by WangDaYeeeeee** [comment]
I just sent a new update to the Google Play Store and GitHub, I fixed this bug in new version.

**Comment by xasx** [comment]
Thanks, works again.
