### ISSUE TITLE
Getting Building Error

### ISSUE THREAD

**Issue by beratsenv** [WangDaYeeeeee/Mysplash#47]
```
ye.mysplash E/AndroidRuntime: FATAL EXCEPTION: main
                                                                     Process: com.wangdaye.mysplash, PID: 5489
                                                                     java.lang.RuntimeException: Unable to start activity ComponentInfo{com.wangdaye.mysplash/com.wangdaye.mysplash.main.view.activity.MainActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'void android.support.design.widget.NavigationView.inflateMenu(int)' on a null object reference
                                                                         at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2927)
                                                                         at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2988)
                                                                         at android.app.ActivityThread.-wrap14(ActivityThread.java)
                                                                         at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1631)
                                                                         at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                         at android.os.Looper.loop(Looper.java:154)
                                                                         at android.app.ActivityThread.main(ActivityThread.java:6682)
                                                                         at java.lang.reflect.Method.invoke(Native Method)
                                                                         at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1520)
                                                                         at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1410)
                                                                      Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'void android.support.design.widget.NavigationView.inflateMenu(int)' on a null object reference
                                                                         at com.wangdaye.mysplash.main.view.activity.MainActivity.initView(MainActivity.java:356)
                                                                         at com.wangdaye.mysplash.main.view.activity.MainActivity.onStart(MainActivity.java:225)
                                                                         at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1256)
                                                                         at android.app.Activity.performStart(Activity.java:6959)
                                                                         at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2890)
                                                                         at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2988) 
                                                                         at android.app.ActivityThread.-wrap14(ActivityThread.java) 
                                                                         at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1631) 
                                                                         at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                         at android.os.Looper.loop(Looper.java:154) 
                                                                         at android.app.ActivityThread.main(ActivityThread.java:6682) 
                                                                         at java.lang.reflect.Method.invoke(Native Method) 
                                                                         at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1520) 
                                                                         at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1410) 

```

Every time building it, showing up. Can you help me? Thanks.

**Comment by WangDaYeeeeee** [comment]
I guess this error should be due to the configuration of the project has a problem, so the ButterKnife is not working properly.
